name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # ruleid: allowed-unsecure-commands
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: log untrusted output
      run: |

        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

        # log untrusted output
        echo "untrusted output"

        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'

    - name: make
      run: make

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: python tools/xiaotea/Scripts/prepareZip_online.py
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: M365_v3_build_${{ github.run_number }}
        retention-days: 5

    - name: CI Commit New Firmware
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add tools/zip_output/FIRM.bin
        git add tools/zip_output/FIRM.bin.enc
        git add tools/zip_output/info.txt
        git commit -m "Add new firmware build [skip ci]" || echo "No changes to commit"
        git push
